name: build-llvm-16.0.6-windows11-x86
on:
  workflow_dispatch:
jobs:
  build-16-0-6:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      # - uses: microsoft/setup-msbuild@v1.1
      - name: setup build deps
        run: |
          choco install -y cmake python3 7zip
          RefreshEnv.cmd
          regsvr32 "%VSINSTALLDIR%\DIA SDK\bin\msdia140.dll"
          regsvr32 "%VSINSTALLDIR%\DIA SDK\bin\amd64\msdia140.dll"
          pip install psutil
      - name: Cache version
        id: cache-llvm
        uses: actions/cache@v3.3.2
        with:
          path: llvm
          key: ${{ runner.os }}-llvm
      - name: checkout llvm
        run: git clone --single-branch --depth 1 --branch llvmorg-16.0.6 https://github.com/llvm/llvm-project llvm
        if: steps.cache-llvm.outputs.cache-hit != 'true'
          
      - name: setup build
        run: |
            mkdir build
            mkdir install
            cmake `
              -S ".\llvm\llvm" `
              -B ".\build" `
              -G "Visual Studio 16 2019" `
              -Thost=x64 `
              -A x64 `
              -DLLVM_ENABLE_PROJECTS="lld;clang" `
              -DLLVM_STATIC_LINK_CXX_STDLIB=true `
              -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_INSTALL_PREFIX=".\install"
            cmake --build .\build --target INSTALL --config Release -j
            7z a -mx9 "LLVM-16.0.6-win64.7z" ".\install\*"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LLVM-16.0.6-win64
          path: LLVM-16.0.6-win64.7z
