name: build-macos
on:
  workflow_dispatch:
    inputs:
      tag-name:
        required: false
        type: string
        description: The tag to upload releases to defaults to v<inputs.llvm-version>
      llvm-version:
        required: true
        type: string
        description: ""
      macos-version:
        required: true
        type: string
        description: ""
      arch:
        required: true
        type: string
        description: ""
      arch-triple:
        required: false
        description: The arch for the output file-name
        type: string
        default: x86_64
  workflow_call:
    inputs:
      llvm-version:
        required: true
        type: string
      macos-version:
        required: true
        type: string
      arch:
        required: true
        type: string
      arch-triple:
        required: false
        description: The arch for the output file-name
        type: string
jobs:
  build:
    runs-on: ${{ inputs.macos-version }}
    steps:
      - uses: actions/checkout@v3
      - name: setup build deps
        run: brew install ninja
      - name: fetch llvm
        run: |
          curl -L https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ inputs.llvm-version }}.tar.gz \
             -o $GITHUB_WORKSPACE/llvm.tar.gz \
          && mkdir $GITHUB_WORKSPACE/llvm \
          && tar -xf $GITHUB_WORKSPACE/llvm.tar.gz --strip-components 1 -C $GITHUB_WORKSPACE/llvm \
          && ls $GITHUB_WORKSPACE/llvm

      - name: setup & build
        run: |
          mkdir -p $GITHUB_WORKSPACE/llvm/build \
            && cd $GITHUB_WORKSPACE/llvm/build \
            && cmake -G "Ninja" -S ../llvm \
              -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/llvm${{ inputs.llvm-version }}" \
              -DCMAKE_BUILD_TYPE="Release" \
              -DLLVM_TARGETS_TO_BUILD="${{ inputs.arch }}" \
              -DLLVM_ENABLE_ASSERTIONS=ON \
              -DLLVM_ENABLE_PROJECTS="clang;lld" \
              -DLLVM_INCLUDE_TESTS=Off \
              -DLLVM_INCLUDE_EXAMPLES=Off \
              -DLLVM_OPTIMIZED_TABLEGEN=On \
            && ninja -C . install
      - name: package results
        run: |
          pushd $GITHUB_WORKSPACE/llvm${{ inputs.llvm-version }} \
            && tar -cJf \
              $GITHUB_WORKSPACE/clang+llvm-${{ inputs.llvm-version }}-${{ inputs.arch }}-apple-darwin.tar.xz \
              . \
            && ls $GITHUB_WORKSPACE \
            && popd
      - name: Upload Release
        uses: ncipollo/release-action@v1
        if: ${{ !github.event.pull_request }}
        with:
          allowUpdates: true
          tag: v${{ (inputs.tag-name || inputs.llvm-version) }}
          name: ${{ (inputs.tag-name || inputs.llvm-version) }}
          makeLatest: false
          artifacts: clang+llvm-${{ inputs.llvm-version }}-${{ (inputs.arch-triple || inputs.arch) }}-apple-darwin.tar.xz
