name: build-windows
on:
  workflow_dispatch:
    inputs:
      llvm-version:
        description: ""
        required: true
        type: string
      windows-version:
        description: ""
        required: true
        type: string
      vs-version:
        description: ""
        required: true
        type: string
  workflow_call:
    inputs:
      llvm-version:
        required: true
        type: string
      windows-version:
        required: true
        type: string
      vs-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{inputs.windows-version}}
    steps:
      - uses: actions/checkout@v3
      - name: setup build deps
        run: |
          choco install -y cmake python3 7zip
          RefreshEnv.cmd
          regsvr32 "%VSINSTALLDIR%\DIA SDK\bin\msdia140.dll"
          regsvr32 "%VSINSTALLDIR%\DIA SDK\bin\amd64\msdia140.dll"
          pip install psutil
      - name: fetch llvm
        run: |
          Invoke-WebRequest -Uri https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ inputs.llvm-version }}.zip -OutFile ./llvm.zip
          New-Item -Path "${{ github.workspace }}" -Name "llvm" -ItemType Directory
          & 7z.exe x llvm.zip -o"llvm-tmp" -y
          Get-ChildItem -Path "llvm-tmp\*\"" -Recurse | Move-Item -Destination "llvm"
          Get-ChildItem -Force -Path "llvm-tmp"
          Get-ChildItem -Force -Path "llvm"
      - name: setup & build
        run: |
            New-Item -Path "${{ github.workspace }}" -Name "build" -ItemType Directory
            New-Item -Path "${{ github.workspace }}" -Name "install" -ItemType Directory
            cmake `
              -S ".\llvm\llvm" `
              -B ".\build" `
              -G "${{ inputs.vs-version }}" `
              -Thost=x64 `
              -A x64 `
              -DLLVM_ENABLE_PROJECTS="lld;clang" `
              -DLLVM_STATIC_LINK_CXX_STDLIB=true `
              -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_INSTALL_PREFIX=".\install"
            cmake --build .\build --target INSTALL --config Release -j
            7z a -mx9 "LLVM-${{ inputs.llvm-version }}-win64.7z" ".\install\*"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LLVM-${{ inputs.llvm-version }}-win64
          path: LLVM-${{ inputs.llvm-version }}-win64.7z
