name: build-llvm-16.0.6-darwin-aarch64
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-16-0-6-macos:
    uses: ./.github/workflows/build-llvm-macos.yml
    with:
      macos-version: macos-latest
      arch: Aarch64
      arch-triple: aarch64
      llvm-version: 16.0.6
