name: build-llvm-16.0.6-darwin-aarch64
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-16-0-6-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/build-llvm-macos.yml
        with:
          macos-version: macos-latest
          arch: Aarch64
          llvm-version: 16.0.6
          arch-triple: aarch64
